name: greet
on:
  workflow_dispatch:
    inputs:
      name:
        description: "your name"
        required: true
      email:
        description: "email"
        required: false
      location:
        description: "location"
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
          echo "- in ${{ github.event.inputs.email }}!"
          echo "- in ${{ github.event.inputs.location }}!"
