name: Summary 
  
on:  
  pull_request:  
    types: [opened]  
  
jobs:  
  summary:  
    name: summary
    runs-on: ubuntu-latest  
    steps:  
      - name: summary
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
      
      
      - name: summary with `actions/github-script`
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `# Result\n
            #### Initialization ok\n
            #### Validation ok\n
            #### Dryrun \n
            <details><summary>Show Plan</summary>
            \`\`\`result\n
            - aaa
            - bbb
            \`\`\`
            </details>
            *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            await core.summary
              .addHeading('Report')
              .addRaw(output)
              .addTable([
                [{data: 'File', header: true}, {data: 'Result', header: true}],
                ['foo.js', 'Pass ✅'],
                ['bar.js', 'Fail ❌'],
                ['test.js', 'Pass ✅']
              ])
              .write()
